name: Python package

on:
  push:
    branches: [ master, actions-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      run: |
        pip install poetry
    - name: Poetry Install Dependencies
      run: |
        poetry install --no-interaction
    - name: pyinstaller
      run: |
        poetry run pyinstaller main.py --clean --onefile
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
          dist/main.exe