name: Create Release

on:
  pull_request:
    types:
      - closed

env:
  APP_NAME: 'BATTERY_WATCH'

jobs:
  create-release:

    if: contains(github.head_ref, 'release')
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      run: |
        pip install poetry
    - name: Poetry Install Dependencies
      run: |
        poetry install --no-interaction
    - name: pyinstaller
      run: |
        poetry run pyinstaller main.py --clean --onefile
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.pull_request.title }}
        tag_name: ${{ github.event.pull_request.title }}
        generate_release_notes: true
        files: dist/main.exe
